### ISSUE TITLE
Caps Lock LED is not present on keyboard; should be implemented in the UI somewhere

### ISSUE THREAD

**Issue by ColtonDRG** [GalliumOS/galliumos-sandy#5]
The presence of a Caps Lock key makes this an issue on this specific Chromebook, others shouldn't have to worry about it. There is no LED to indicate the state of Caps Lock. This should be implemented in the GUI somewhere, perhaps in the form of an icon indicator in the system notification tray.

**Comment by coolstar** [comment]
On certain thinkpads that don't have LED's for these buttons (like mine) they use a HUD at the bottom right. Just giving some ideas :)

![image](https://cloud.githubusercontent.com/assets/1431548/9723357/5444bd8a-5574-11e5-970e-845d766fbb75.png)

**Comment by ColtonDRG** [comment]
That's a little too intrusive for my liking. I am using this GNOME extension on my current setup and quite like it. https://extensions.gnome.org/extension/36/lock-keys/ There must be an XFCE version somewhere. It also might be worth looking into a MATE version as I would like to support MATE in future releases as well.

**Comment by ColtonDRG** [comment]
http://goodies.xfce.org/projects/panel-plugins/xfce4-kbdleds-plugin I think this will work fine, but it's not in the repos, so we should include it in our repos and add it as a dep for this package. Unfortunately, I have no idea how the repos work, so I need to either learn from @hugegreenbug, or have him do it for me.

**Comment by reynhout** [comment]
Wow this is old. :) CAPSLOCK does exist in the normal keyboard layout now, but I'm not sure if it works on the C710. In any event, closing ticket and disabling issues for this repo. All followups to https://github.com/GalliumOS/galliumos-distro. Thanks!
