### ISSUE TITLE
Right Mouse Click doesn't work

### ISSUE THREAD

**Issue by kaffeeringe** [GalliumOS/galliumos-sandy#7]
Hi!

The right click on my Acer C710 doesn't work. Is it just no set or how can I find out, if it's broken?

**Comment by reynhout** [comment]
@kaffeeringe right mouse click is configured as "two-fingered click" instead. If you can't get used to that, I think there is a thread on https://reddit.com/r/GalliumOS that describes the necessary config changes. If you can't find it, post an inquiry. :)

I'm going to close this ticket and turn off issues for this repo, we try to keep them all in https://github.com/GalliumOS/galliumos-distro.
