### ISSUE TITLE
Keyboard Layout

### ISSUE THREAD

**Issue by kaffeeringe** [GalliumOS/galliumos-sandy#8]
Hi!

On my Acer C710 the Alt-keys and the search-keys are not working. Can I enable them somehow?

**Comment by reynhout** [comment]
@kaffeeringe have you read https://wiki.galliumos.org/Media_keys_and_default_keybindings ?

If you're still having trouble, drop into https://galliumos.org/irc and check with ColtonDRG. He has a PARROT too and will be able to answer your questions.

Closing this ticket and turning off issues for this repo. Please post follow ups in https://github.com/GalliumOS/galliumos-distro . Thanks.
